### ISSUE TITLE
Crash when issuing wrong argument name

### ISSUE THREAD

**Issue by markusressel** [markusressel/telegram-click#19]
**Describe the bug**
A command with a single argument fails to execute when naming it wrong.

**To Reproduce**
1. Create a command with a single argument, f.ex. `/a --b` of type `bool`
2. Issue the following command in the chat: `/a --c`
3. See error

**Expected behavior**
Print a message that the given argument is unknown/unsupported.

**Additional context**
```
2020-02-27 22:15:56,739 - root - ERROR - Error in callback
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/telegram_click/decorator.py", line 113, in wrapper
cmd, parsed_args = parse_telegram_command(bot.username, message.text, arguments)
File "/usr/local/lib/python3.8/site-packages/telegram_click/util.py", line 214, in parse_telegram_command
parsed_args = parse_command_args(args, expected_args)
File "/usr/local/lib/python3.8/site-packages/telegram_click/util.py", line 131, in parse_command_args
named, floating = split_named_args(str_args)
File "/usr/local/lib/python3.8/site-packages/telegram_click/util.py", line 108, in split_named_args
named_item = (remove_naming_prefix(arg), str_args[i + 1])
IndexError: list index out of range
```

**Comment by markusressel** [comment]
Since #21 removed this entire method, this issue will be closed for now.
